### ISSUE TITLE
Is there a arXiv paper?

### ISSUE THREAD

**Issue by chengwei0427** [piluohong/hc-lio#1]
Hi, @piluohong 
Nice work! And is there a arXiv paper?
And the test data(cotton_1/2/3) is very challenging. I am looking forward to your paper.

**Comment by piluohong** [comment]
Hello, we have not posted on any pre-printed website. You can try the DLIO solution, which we use as a blueprint. DLIO's strategy is pretty good, but it's very bad for dynamic scenes. We mainly focus on the application research of agricultural robots, so there are fewer dynamic cases.

> Hi, @piluohong Nice work! And is there a arXiv paper? And the test data(cotton_1/2/3) is very challenging. I am looking forward to your paper.

**Comment by chengwei0427** [comment]
Thanks for your reply.

**Comment by chengwei0427** [comment]
Hi, @piluohong 
Thanks for your contributions to the open source community.
Can you describe the contribution of this project that is different from dlio?
Add a backend, and use vgicp instead of gicp?

**Comment by piluohong** [comment]
> Hi, @piluohong Thanks for your contributions to the open source community. Can you describe the contribution of this project that is different from dlio? Add a backend, and use vgicp instead of gicp?

odom.cc has a decription.
