### ISSUE TITLE
Request access to dataset

### ISSUE THREAD

**Issue by lacie-life** [piluohong/hc-lio#2]
Thank you very much for making this code available. I am testing your code, but accessing the dataset with the link you provided requires access permissions. Can you give me access? My email is 00sao00ios00@gmail.com 

Thank you very much !!!

**Comment by piluohong** [comment]
> Thank you very much for making this code available. I am testing your code, but accessing the dataset with the link you provided requires access permissions. Can you give me access? My email is [00sao00ios00@gmail.com](mailto:00sao00ios00@gmail.com)
> 
> Thank you very much !!!

Sorry, I make a mistake with the limits of authority. Now, you can try to download them.

**Comment by piluohong** [comment]
https://drive.google.com/drive/folders/1-SLxUejiFGY_PzGn1oLpMKWUoBMMOyx5?usp=drive_link

**Comment by lacie-life** [comment]
Thank you, it worked
